
services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app

  app:
    build: ./docker/php
    container_name: laravel_app
    volumes:
      - .:/var/www
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firstPractice
    ports:
      - "3307:3306"
    volumes:
      - laravel_db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  laravel_db_data:

networks:
  app-network:
    driver: bridge
